inherit_gem:
  retrieva-cop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.1
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "node_modules/**/*"
    - "config.ru"
    - "config/puma.rb"
    - "config/unicorn.rb"
    - "Capfile"
    - "**/*.spec"  # .spec file should be an RPM spec file not an RSpec file
    - "bin/**/*"
    - "config/**/*"
RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'
