version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  slack: circleci/slack@3.4.2

jobs:
  rubocop:
    docker:
      - image: circleci/ruby:3.0.2-node-browsers-legacy
      - image: circleci/postgres:13.4
        environment:
          POSTGRES_USER: miyatani_el_training
          POSTGRES_DB: miyatani_el_training_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      RAILS_ENV: test
      APP_DATABASE_HOST: "127.0.0.1"
      DB_USER: miyatani_el_training
    working_directory: ~/miyatani_el_training
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Rubocop
          command: bundle exec rubocop
  test:
    docker:
      - image: circleci/ruby:3.0.2-node-browsers-legacy
      - image: circleci/postgres:13.4
        environment:
          POSTGRES_USER: miyatani_el_training
          POSTGRES_DB: miyatani_el_training_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      RAILS_ENV: test
      APP_DATABASE_HOST: "127.0.0.1"
      DB_USER: miyatani_el_training
    working_directory: ~/miyatani_el_training
    steps:
      - checkout
      - ruby/install-deps
      - run: yarn install
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  rubocop_and_test:
    jobs:
      - rubocop
      - test:
          requires:
            - rubocop
      - slack/status:
          success_message: ':circleci-pass: $CIRCLE_BRANCH のテストが完了しました'
          failure_message: ':circleci-fail: $CIRCLE_BRANCH のテストが失敗しました'
          webhook: '${SLACK_WEBHOOK}'
